default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 28051993
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sites_development

test:
  <<: *default
  database: sites_test

production:
  url: <%= ENV['postgres://vglixrdyaiuubr:s6LR6Rx_YaI5ax1kZ7hSPJ4nP3@ec2-54-83-5-151.compute-1.amazonaws.com:5432/d25ebm91cgi65i'] %>
